---
- name: Download cig binary.
  become: yes
  get_url:
    url: "{{ cig_github_repo_url }}/releases/download/v{{ cig_version }}/cig_{{ ansible_system }}_{{ ansible_architecture }}"
    dest: /usr/local/bin/cgi
    mode: "0755"
    # Hard-coding the checksum as a guard against regression.
    sha256sum: "{{ cig_checksum }}"
